### ISSUE TITLE
ReferenceArrayField doesn't work

### ISSUE THREAD

**Issue by chirita-alex** [aymendhaya/ra-data-firebase-client#13]
```
import React from 'react';
import { List, ReferenceArrayField, SingleFieldList, TextField, ChipField, Datagrid } from 'react-admin';

export const Orders = props => (
  <List {...props}>
    <Datagrid>
      <TextField label="State" source="state" />
      <ReferenceArrayField label="Products" reference="orderItem" source="items">
        <SingleFieldList>
          <ChipField source="price" />
        </SingleFieldList>
      </ReferenceArrayField>
    </Datagrid>
  </List>
);
```

### I have this piece of code and returns me an error. I'm struggling with this for a long time. What I did wrong? It is a bug? 

<img width="445" alt="Screenshot 2019-10-17 at 23 35 49" src="https://user-images.githubusercontent.com/30051488/67045688-7c27f700-f137-11e9-80c8-ec50d31750f1.png">

<img width="487" alt="Screenshot 2019-10-17 at 23 36 11" src="https://user-images.githubusercontent.com/30051488/67045689-7cc08d80-f137-11e9-9883-23286c0a5b13.png">

<img width="924" alt="Screenshot 2019-10-17 at 23 35 07" src="https://user-images.githubusercontent.com/30051488/67045690-7cc08d80-f137-11e9-9216-483da814a5cc.png">

**Comment by bayareacoder** [comment]
Firebase RT database cannot handle arrays, while react-admin expects 'many' references in an array. So we need a convention to store a many reference as an object that also identifies order, like this:
`{ <fk1> : 1, <fk2>: 2,...}` and then methods to convert this to an array `[<fk1>,<fk2>,..]` upon fetch, and vice versa upon save. We assume that such a many reference is stored under a key that ends in `Ids` so that only the values of those keys are converted (and not other nested objects).

This can be done by modifying the get & save filters in file RestProvider.js, as follows:
```
  // Converts values of keys ending with `Ids`, assumed to be of a shape { <fk1> : <seq1>, <fk2>: <seq2>, ...},
  // to [<fk1>,<fk2>,...] when <seq1> < <seq2>
  const _getFilter = entry => {
    const ret = {};
    Object.keys(entry).forEach(key => {
      ret[key] = key.endsWith('Ids')
        ? Object.keys(entry[key]).sort((a, b) => entry[key][a] - entry[key][b])
        : entry[key];
    });
    return ret;
  };

  // Converts values of keys ending with `Ids`, assumed to be of a shape [<fk1>,<fk2>,...] to
  // { <fk1> : 1, <fk2>: 2, ...}
  const _saveFilter = entry => {
    const ret = {};
    Object.keys(entry).forEach(key => {
      if (key.endsWith('Ids')) {
        const tmp = {};
        entry[key].forEach((fk, index) => (tmp[fk] = index + 1));
        ret[key] = tmp;
      } else {
        ret[key] = entry[key];
      }
    });
    return ret;
  };
  const firebaseSaveFilter = options.firebaseSaveFilter
    ? options.firebaseSaveFilter
    : // : data => data;
      _saveFilter;

  const firebaseGetFilter = options.firebaseGetFilter
    ? options.firebaseGetFilter
    : // : data => data;
      _getFilter;
```

I have made these changes and now ReferenceMany works.

**Comment by aymendhaya** [comment]
Hi, please check the v3 release
