### ISSUE TITLE
ReferenceField for nested collections?

### ISSUE THREAD

**Issue by shamshiranees** [aymendhaya/ra-data-firebase-client#15]
![Screenshot 2019-11-07 at 5 36 41 PM](https://user-images.githubusercontent.com/34855187/68387803-3209c280-0185-11ea-9c2e-612dac1b45a6.png)
I am having above db structure.
As the exams have dynamic keys. How could I list all questions of the exam.

**Comment by bayareacoder** [comment]
This is not a question related to a ReferenceField since you're not referencing any other resource; you're embedding everything inside the same resource. 
To answer your question, I don't think you can with your data structure. If you want one object per exam, then you would need:
```
exams : {
 key1: {
   questions: {
     key1a: {
       ...
     },
     key1b: {
       ...
     }
   },
  key2: {
  ...
  }
}
```

Then subscribe to `exams` resource and you will get an array of objects, flattened 1 level, i.e. [ {key: key1, questions: {..}}, ...]. 

Alternatively you could have 2 resources (exams, questions) and have a 1-to-many relationship from exams to question. But 1-to-many has issues also with this data provider I believe. See: https://github.com/aymendhaya/ra-data-firebase-client/issues/13#issuecomment-558419713

**Comment by aymendhaya** [comment]
Hi, please check the v3 release
