### ISSUE TITLE
Project still being developed?

### ISSUE THREAD

**Issue by brownieboy** [aymendhaya/ra-data-firebase-client#23]
No updates for over 2 years.   Is this project still being developed?

I’ve been struggling with getting it to work with the latest versions of React Admin and Firebase.  I was going to post my findings here if anybody is interested.

**Comment by brownieboy** [comment]
I'll take that as a "no" then.

I've managed to get it working with the latest versions of React Admin and Firebase, but it took quite a hefty rewrite.  I couldn't even get this repo to _build_ at first !
**Update**
Repo built fine when I just tried it again.  I think the problem was in my own Node set up, not in the repo  🤦‍♂️.

No point in submitting it as a PR if there's nobody maintaining the project though.

If I get no further response, I'll roll it out as a new package.

**Comment by aymendhaya** [comment]
@brownieboy , feel free to make a PR if you are intrested. 

I planned to update the package by the end of May due to a lack of free time actually.

Sad to hear that it wasn't easy for you to build the project, it's a simple _react-react-library_ template tho :)

All kind suggestions are welcome meanwhile !

I will close this issue then !

**Comment by brownieboy** [comment]
Good stuff, @aymendhaya .

The repo built fine when I just tried it again, fyi. I think the problem was in my own Node set up, not in the repo itself.  My bad 🤦‍♂️.   I've updated my comment above accordingly.

I'll submit a PR for my changes.
